// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq7IJrfibap6K7ZB0JKCSjG2lD9Fj3qoE',
    appId: '1:18647088992:web:e36a7344a8a19b42f6e805',
    messagingSenderId: '18647088992',
    projectId: 'laptopstore-915bc',
    authDomain: 'laptopstore-915bc.firebaseapp.com',
    storageBucket: 'laptopstore-915bc.appspot.com',
    measurementId: 'G-929HEEH1PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YQD4AhdjCh8Eaq-kmXwVkfNz4Ew2b1c',
    appId: '1:18647088992:android:5ca26aa756c9f37ef6e805',
    messagingSenderId: '18647088992',
    projectId: 'laptopstore-915bc',
    storageBucket: 'laptopstore-915bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_U26d6XoDhimj5k7Oap-L-kERebrv04',
    appId: '1:18647088992:ios:0a44655f58eaec72f6e805',
    messagingSenderId: '18647088992',
    projectId: 'laptopstore-915bc',
    storageBucket: 'laptopstore-915bc.appspot.com',
    iosBundleId: 'com.example.laptopstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_U26d6XoDhimj5k7Oap-L-kERebrv04',
    appId: '1:18647088992:ios:0a44655f58eaec72f6e805',
    messagingSenderId: '18647088992',
    projectId: 'laptopstore-915bc',
    storageBucket: 'laptopstore-915bc.appspot.com',
    iosBundleId: 'com.example.laptopstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq7IJrfibap6K7ZB0JKCSjG2lD9Fj3qoE',
    appId: '1:18647088992:web:e11311bb79f63bf4f6e805',
    messagingSenderId: '18647088992',
    projectId: 'laptopstore-915bc',
    authDomain: 'laptopstore-915bc.firebaseapp.com',
    storageBucket: 'laptopstore-915bc.appspot.com',
    measurementId: 'G-0J8X5E074M',
  );
}
